import Link from "next/link";
import Badge from "@/app/components/ui/Badge";
import Button from "@/app/components/ui/button";
import { CALL_TO_ACTION_CONTENT } from "@/app/landingpage/config/landingContent";
import GradientText from "../../Effects/TextEffects/GradientText";

const CallToAction = () => {
  return (
    <section
      className="
                relative 
                flex min-h-[100vh] 
                items-center 
                justify-center 
                overflow-hidden 
                px-4 
                py-16
            "
    >
      <div
        className="
                    pointer-events-none 
                    absolute 
                    inset-0 
                    bg-[linear-gradient(125deg,rgba(1,82,148,0.34),rgba(5,18,38,0.9)_45%,rgba(13,123,204,0.24))]
                "
      />
      <div
        className="
                    pointer-events-none
                    absolute
                    inset-0
                    opacity-35
                    [background-image:radial-gradient(rgba(152,202,253,0.2)_1px,transparent_1px)]
                    [background-size:22px_22px]
                "
      />
      <div
        className="
                    pointer-events-none
                    absolute
                    -left-24
                    top-10
                    h-72
                    w-72
                    rounded-full
                    bg-[#015294]/25
                    blur-3xl
                "
      />
      <div
        className="
                    pointer-events-none
                    absolute
                    -right-20
                    bottom-4
                    h-80
                    w-80
                    rounded-full
                    bg-[#0d7bcc]/20
                    blur-3xl
                "
      />

      <div
        className="
                    relative 
                    z-10
                    mx-auto 
                    flex 
                    w-full 
                    max-w-6xl 
                    flex-col 
                    items-center 
                    gap-10 
                    px-5 
                    py-8 
                    md:px-8 
                    md:py-10
                "
      >
        <div
          className="
                        flex 
                        w-full 
                        max-w-5xl 
                        flex-col 
                        items-center 
                        gap-6 
                        text-center
                    "
        >
          <GradientText
            colors={["#015294", "#98cafd", "#015294", "#a2d6fc", "#015294"]}
            animationSpeed={8}
            direction="horizontal"
            showBorder={false}
            fontSize="clamp(2rem,7.2vw,2.9rem)"
          >
            {CALL_TO_ACTION_CONTENT.heading}
          </GradientText>

          <p
            className="
                            max-w-3xl 
                            text-sm 
                            leading-7 
                            text-white/70 
                            md:text-base
                        "
          >
            {CALL_TO_ACTION_CONTENT.subtitle}
          </p>

          <div
            className="
                            flex 
                            flex-wrap 
                            items-center 
                            justify-center 
                            gap-3
                        "
          >
            {CALL_TO_ACTION_CONTENT.highlights.map((item) => (
              <Badge
                key={item}
                variant="glass"
                className="
                                    px-4 
                                    py-2 
                                    text-xs 
                                    uppercase 
                                    tracking-[0.09em] 
                                    text-white/70
                                "
              >
                {item}
              </Badge>
            ))}
          </div>

          <div
            className="
                            flex 
                            flex-wrap 
                            items-center 
                            justify-center 
                            gap-3 
                            pt-1
                        "
          >
            <Link href={CALL_TO_ACTION_CONTENT.primaryButtonHref}>
              <Button
                className="
                                    h-11 
                                    rounded-full 
                                    border 
                                    border-[#98cafd]/40 
                                    bg-[linear-gradient(145deg,rgba(1,82,148,0.62),rgba(13,123,204,0.4))] 
                                    px-6 
                                    text-sm 
                                    font-semibold 
                                    text-white 
                                    shadow-[0_10px_24px_rgba(1,82,148,0.38),inset_0_1px_0_rgba(218,240,255,0.4)] 
                                    backdrop-blur-md 
                                    backdrop-saturate-150 
                                    hover:bg-[linear-gradient(145deg,rgba(1,82,148,0.74),rgba(13,123,204,0.52))]
                                "
              >
                {CALL_TO_ACTION_CONTENT.primaryButtonLabel}
              </Button>
            </Link>

            <Link href={CALL_TO_ACTION_CONTENT.secondaryButtonHref}>
              <Button
                variant="ghost"
                className="
                                    h-11 
                                    rounded-full 
                                    border 
                                    border-[#98cafd]/30 
                                    bg-[linear-gradient(145deg,rgba(255, 255, 255, 0.34),rgba(13,123,204,0.2))] 
                                    px-6 
                                    text-sm 
                                    font-semibold 
                                    text-white 
                                    shadow-[inset_0_1px_0_rgba(218,240,255,0.3)] 
                                    backdrop-blur-md 
                                    backdrop-saturate-150 
                                    hover:bg-[linear-gradient(145deg,rgba(171, 171, 171, 0.46),rgba(13,123,204,0.28))] 
                                    hover:text-white
                                "
              >
                {CALL_TO_ACTION_CONTENT.secondaryButtonLabel}
              </Button>
            </Link>
          </div>
        </div>

        <div
          className="
                        w-full 
                        max-w-4xl 
                        border-t 
                        border-white/10 
                        pt-8 
                        text-center
                    "
        >
          <GradientText
            colors={["#015294", "#98cafd", "#015294", "#a2d6fc", "#015294"]}
            animationSpeed={8}
            direction="horizontal"
            showBorder={false}
            fontSize="clamp(1.8rem,6.5vw,3.25rem)"
          >
            {CALL_TO_ACTION_CONTENT.newsletterTitle}
          </GradientText>

          <p
            className="
                            mx-auto 
                            mt-3 
                            max-w-3xl 
                            text-base 
                            leading-8 
                            text-white/80 
                            md:text-lg
                        "
          >
            {CALL_TO_ACTION_CONTENT.newsletterSubtitle}
          </p>

          <form
            className="
                            mx-auto 
                            mt-7 
                            flex 
                            w-full 
                            max-w-4xl 
                            flex-col 
                            gap-3 
                            md:flex-row 
                            md:items-center
                        "
          >
            <input
              type="email"
              name="email"
              required
              placeholder={CALL_TO_ACTION_CONTENT.newsletterPlaceholder}
              className="
                                h-14 
                                w-full 
                                rounded-full 
                                bg-white/10 
                                px-6 
                                text-lg 
                                text-white 
                                placeholder:text-white/50 
                                outline-none 
                                ring-1 
                                ring-white/25 
                                transition 
                                focus:ring-2 
                                focus:ring-[#98cafd]/60
                            "
            />
            <Button
              type="submit"
              className="
                                h-14 
                                min-w-[180px] 
                                rounded-full 
                                border 
                                border-[#98cafd]/45 
                                bg-[linear-gradient(145deg,rgba(1,82,148,0.68),rgba(13,123,204,0.46))] 
                                px-8 
                                text-lg 
                                font-semibold 
                                text-white 
                                shadow-[0_12px_34px_rgba(1,82,148,0.45),inset_0_1px_0_rgba(218,240,255,0.45)] 
                                backdrop-blur-md 
                                backdrop-saturate-150 
                                hover:bg-[linear-gradient(145deg,rgba(1,82,148,0.78),rgba(13,123,204,0.58))]
                            "
            >
              {CALL_TO_ACTION_CONTENT.newsletterButtonLabel}
            </Button>
          </form>

          <div
            className="
                            mt-4 
                            flex 
                            flex-wrap 
                            items-center 
                            justify-center 
                            gap-2
                        "
          >
            {CALL_TO_ACTION_CONTENT.newsletterTrustPills.map((pill) => (
              <Badge
                key={pill}
                variant="glass"
                className="
                                    px-3 
                                    py-1 
                                    text-[11px] 
                                    uppercase 
                                    tracking-[0.08em] 
                                    text-white/70
                                "
              >
                {pill}
              </Badge>
            ))}
          </div>
        </div>
      </div>
    </section>
  );
};

export default CallToAction;
